### ISSUE TITLE
There's something wrong with the Toy Gridworlds...

### ISSUE THREAD

**Issue by jvmncs** [david-lindner/safe-grid-gym#15]
Something about the toy gridworlds is broken.  It looks like a tabular Q-learner learns the worst-case policy instead of the best case one, despite thoroughly exploring the environment.

For reference, here's the command I'm using:
`python main.py -L test-log/<env_name> -E 1000 -V 100 -EE 50 <env_name> tabular-q -l .2 -dl 6000`

When `<env_name>` is set to `sokoban`:
<img width="1067" alt="screen shot 2019-01-11 at 6 12 35 pm" src="https://user-images.githubusercontent.com/7891333/51064258-ca1e3600-15cc-11e9-9d30-5262a05ace67.png">

When `<env_name>` is set to `way`:
<img width="1068" alt="screen shot 2019-01-11 at 6 12 50 pm" src="https://user-images.githubusercontent.com/7891333/51064244-be327400-15cc-11e9-85ba-b2bd08900193.png">

When `<env_name>` is set to `corners`:
<img width="1068" alt="screen shot 2019-01-11 at 6 13 01 pm" src="https://user-images.githubusercontent.com/7891333/51064259-ca1e3600-15cc-11e9-995c-5b08c55143d6.png">

**Comment by david-lindner** [comment]
The environments seem to work as expected. I wrote some tests and checked that they have rewards and corruptions as designed, see https://github.com/david-lindner/safe-grid-gym/pull/17

I am not entirely sure what is going on with the q learning in your example. However, it seems to me that it is just a matter of the parameters of the agent. Letting it run longer, works better for me. With the call

```
python main.py -L test-log/corners -E 100000 -V 100 -EE 1000 corners tabular-q -l .2 -dl 100000
```

I get the following

![image](https://user-images.githubusercontent.com/16326959/51074249-1a54d100-167d-11e9-98c9-eddfb4541c27.png)

which looks quite good to me. The agent seems to learn the optimal policy w.r.t the hidden reward first, because it does not get around to exploring the corrupt states in the corners during the training. An even longer run with a slower epsilon decay should make it learn the corrupt policy here. Can you try if that works for you?

**Comment by timorl** [comment]
Isn't this trying to use value predictors with non-MDP environments? Because it seems like the effect I was describing in [that paper I was writing](https://openreview.net/forum?id=S1llBiR5YX) (in particular see section Axis walk). Tl;dr if you try going to a state with higher expected value and at every step you compute the value to be more or less the rest of a finite trajectory, then quite often the states later in the trajectory have lower value. Therefore the initial state which has value [trajectory length] times [reward at every step]  (not quite constant, but close enough) will act as an attractor.

**Comment by timorl** [comment]
As for solutions, setting an aggresively small discount might help. Alternatively extending the length of trajectories, or adding time at every step (probably a mediocre idea, this is no longer a nice gridworld then).

**Comment by jvmncs** [comment]
Good stuff! I think we can close this, I was just using the tabular-q agent to make sure that the main connections were working properly for these environments.  Shouldn't have been so lazy with the testing, and also probably shouldn't have been coding at 2am :D

**Comment by jvmncs** [comment]
Just a follow up, ran the experiment again with longer epsilon decay rate (red) and compared with @david-lindner's original (orange): 
<img width="1067" alt="screen shot 2019-01-13 at 1 29 10 am" src="https://user-images.githubusercontent.com/7891333/51082322-cc6ab800-16d2-11e9-8f87-4d314617954d.png">
